# Generated by Django 3.2.18 on 2023-04-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=10)),
                ('companyaddress', models.TextField(max_length=100)),
                ('contactnumber', models.CharField(max_length=10)),
                ('companyimage', models.ImageField(default='null.jpg', upload_to='pic')),
            ],
        ),
    ]
